### ISSUE TITLE
[Docs] Organization able to monitor device status (online ,offline)

### ISSUE THREAD

**Issue by truonghoangduy** [GDSC-HSU/gateway#17]
### EPIC : 
An organization able to monitor device status (online , offline)

### Description : 
As devices (mobile_app) are working organizations want to check the device connection status. So that they could identify in real-time does the device is still functional (online) or has been shut down (offline).

#19 After doing research we are using MQTT for this feature.

- [x] Mobile able to connect to ours Backend MQTT broker with credentail (device-id, username, password)
- [x] Having security layer in MQTT subscriber detail in this link https://github.com/moscajs/aedes/issues/513 , and aedes server impl https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#handler-authenticate-client-username-password-callback.
- [x] When the device has been created by #12  backend will create the device connection collection but the status going to be **offfline as default**.
- [x] Device connect/disconnect event occurs will be saved in (firestore collection)

----
#### Ex meaning for suggestion, you could delare your own impl if you not cool with it fill free to notify me
Ex: Firestore collection
```js
var device_connection = firestore.col("device-status").col("device-id").{}
```

Ex: Stored object
```yml
status: offline|online
timespan: int "Based on this we could know what time does the device has been in those statuses"
```

**Comment by DangCao1999** [comment]
the status will be 0|1 not offline|online
