### ISSUE TITLE
[Backend] Research MQTT does the protocol could implement feature the device to connection status. (online, or offline)

### ISSUE THREAD

**Issue by truonghoangduy** [GDSC-HSU/gateway#19]
Here are some detail about MQTT, blog post could help you research an solution

- MQTT allows client to connect to broker with (username, password).

- MQTT protocol has session, and Qos level. Meaning that the broker know when device has been disconnected

- ([copy form](https://community.openhab.org/t/how-to-check-client-device-offline/10519)) MQTT **Last Will and Testament** (**LWT**): when the MQTT broker detects that the client is no longer connected it will publish the LWT message to the configured topic (note LWT is configured on the remote client, not in OH). Then create a switch Item to subscribe for those LWT messages and flip it off when you see a LWT message and back ON when you see any other message (use a rule).

- **LWT** vietnamese blog (thông báo cho các khách hàng khác về một khách hàng **bị ngắt kết nối một cách vô duyên**.) : https://vidieukhien.xyz/2020/03/22/mqtt-tutorial-mqtt-last-will-and-testament/

- **LWT best practice** https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

- **Flutter LWT** : [implement link](https://github.com/shamblett/mqtt_client/blob/1b014e8ea793415bb0e8ed37d29ac9a763a009db/example/mqtt_server_client.dart#L74)

- Topic for status : org/{org-name}/device/{device-id}/status.

- Requirement for near realtime is not required (heart-beat or ping is okie).

---
Google Cloud Solution

GCP has a solution for it: https://stackoverflow.com/questions/54609757/google-core-iot-device-offline-event-or-connection-status , but it has required Stackdirver(GCP monitor tool) to monitor IoT_Core for device disconnection

relatied to GCP solution : 
[persistent-device-connection-status](https://stackoverflow.com/questions/63224303/persistent-device-connection-status-over-mqtt-with-jwt-using-gcp-iot-core)
[google-cloud-detecting-offline-devices](https://stackoverflow.com/questions/54806258/google-cloud-detecting-offline-devices)

Stuff has been proved
- [x] Flutter client able to connect to broker with MQTT v3.1
- [x] Authenticate custom Aedes  broker

**Comment by DangCao1999** [comment]
Implement Broker embedded with express
