### ISSUE TITLE
[Web] Device Management Page

### ISSUE THREAD

**Issue by truonghoangduy** [GDSC-HSU/gateway#36]
Allow users to see all their device belong to their orgnaization.

- [x] Design UI ( I suggest table view) 
- [x] Show basic device information (id,name , location , tag, status)
- [x] For realtime using Firestore

---
Some noted in table nice to have

- In table click to device allow them to navigate to "Device Detail Page"
- In table having a selection for remove device,
- Having a button allows the user to add new devices and route them to the "Create new Device Page"

**Comment by DangCao1999** [comment]
https://github.com/GDSC-HSU/gateway-dashboard/pull/3

**Comment by DangCao1999** [comment]
https://github.com/GDSC-HSU/gateway-dashboard/pull/3
